Algoritmo "cateroriadoatleta"
// Autor(a)    : João Lucas
// Data atual  : 28/09/2017
Var
 idade:inteiro
Inicio
 escreva ("Qual é a idade do atleta?")
 leia (idade)
  caso 5 até 7
   escreva ("infantil A")
   caso 8 até 10
    escreva ("infantil B")
   caso 11 até 13
    escreva ("juvenil A")
   caso 14 até 17
    escreva ("juvenil B")
   caso 18 até 1000
    escreva ("senior")

Fimalgoritmo